baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Adrianna Jefri-Tan"
theme = "anatole"
summarylength = "10"
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Hi, I'm Adrianna Tan"
author = "Adrianna Tan"
description = "Director of Product Management at San Francisco Digital Services"
profilePicture = "images/profile.jpg"
keywords = "product management, product, startup, founder, mentorship"
favicon = "favicons/"
mainSections = ["posts"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false

# Formspree contact form
contactFormAction = "https://formspree.io/f/xknkwjdw"

# Read More links for truncated summaries
readMore = true

## Math settings
[params.math]
enable = false

## Social links
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/adriannatan/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/skinnylatte/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/skinnylatte"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "email"
url = "mailto:adrianna@jefritan.com"

## Menu Items 

[menu]

   [[menu.main]]
   name = "Home"
   identifier = "home"
   weight = 100
   url = "/"

   [[menu.main]]
   name = "Posts"
   weight = 200
   identifier = "posts"
   url = "/posts"

   [[menu.main]]
   name = "About"
   weight = 300
   identifier = "about"
   url = "/about/"
 
   [[menu.main]]
   name = "Contact"
   weight = 400
   identifier = "contact"
   url = "/contact/"
